// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe3zSOpQWLQQalCQEPUZb_Cy04nx45jP8',
    appId: '1:1064835234426:web:9da2a19b1572d58f0719c3',
    messagingSenderId: '1064835234426',
    projectId: 'fluttermagang',
    authDomain: 'fluttermagang.firebaseapp.com',
    storageBucket: 'fluttermagang.firebasestorage.app',
    measurementId: 'G-QL07269KJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8l30jfirEYzDsUXiq09QJiT6Kr9rzalA',
    appId: '1:1064835234426:android:f2c4998be033be800719c3',
    messagingSenderId: '1064835234426',
    projectId: 'fluttermagang',
    storageBucket: 'fluttermagang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUW2G7LF_zdqA--Tey3yJblQeB8-Z01_Q',
    appId: '1:1064835234426:ios:4e8d7f842407836c0719c3',
    messagingSenderId: '1064835234426',
    projectId: 'fluttermagang',
    storageBucket: 'fluttermagang.firebasestorage.app',
    iosClientId: '1064835234426-q0sddr2hn0kqk2t13bcfm2bjd0n844gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.rkomKampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUW2G7LF_zdqA--Tey3yJblQeB8-Z01_Q',
    appId: '1:1064835234426:ios:4e8d7f842407836c0719c3',
    messagingSenderId: '1064835234426',
    projectId: 'fluttermagang',
    storageBucket: 'fluttermagang.firebasestorage.app',
    iosClientId: '1064835234426-q0sddr2hn0kqk2t13bcfm2bjd0n844gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.rkomKampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe3zSOpQWLQQalCQEPUZb_Cy04nx45jP8',
    appId: '1:1064835234426:web:48225bb21663afc90719c3',
    messagingSenderId: '1064835234426',
    projectId: 'fluttermagang',
    authDomain: 'fluttermagang.firebaseapp.com',
    storageBucket: 'fluttermagang.firebasestorage.app',
    measurementId: 'G-263E7D9V12',
  );
}
